set -g prefix C-b
bind C-b send-prefix
set -g mouse on
set -g history-limit 99999
set -g default-terminal "xterm-256color"
set -as terminal-overrides ',xterm-256color:Tc'
set -gq allow-passthrough on
set -g bell-action any
# Machine-specific overrides
source-file -q ~/Dropbox/etc/laptop/tmux.conf.local
source-file -q ~/.tmux.conf.local
